"use client"

export const indianEarthquakeData = [
  {
    id: 1,
    magnitude: 4.3,
    location: "Kutch, Gujarat",
    time: "2 hours ago",
    depth: "10.5km",
    intensity: "Light",
    coordinates: { lat: 23.7337, lng: 69.8597 },
  },
  {
    id: 2,
    magnitude: 3.6,
    location: "Uttarakhand",
    time: "5 hours ago",
    depth: "8.2km",
    intensity: "Light",
    coordinates: { lat: 30.0668, lng: 79.0193 },
  },
  {
    id: 3,
    magnitude: 5.2,
    location: "Andaman Islands",
    time: "Yesterday",
    depth: "15.7km",
    intensity: "Moderate",
    coordinates: { lat: 11.7401, lng: 92.6586 },
  },
  {
    id: 4,
    magnitude: 2.8,
    location: "Himachal Pradesh",
    time: "Yesterday",
    depth: "5.3km",
    intensity: "Weak",
    coordinates: { lat: 31.1048, lng: 77.1734 },
  },
  {
    id: 5,
    magnitude: 4.7,
    location: "Kashmir Valley",
    time: "3 days ago",
    depth: "12.1km",
    intensity: "Light",
    coordinates: { lat: 34.0837, lng: 74.7973 },
  },
  {
    id: 6,
    magnitude: 6.3,
    location: "Nepal-India Border",
    time: "1 week ago",
    depth: "35.2km",
    intensity: "Strong",
    coordinates: { lat: 28.3949, lng: 84.124 },
  },
  {
    id: 7,
    magnitude: 5.8,
    location: "Nicobar Islands",
    time: "2 weeks ago",
    depth: "28.5km",
    intensity: "Moderate",
    coordinates: { lat: 6.9319, lng: 93.929 },
  },
  {
    id: 8,
    magnitude: 4.5,
    location: "Maharashtra-Gujarat Border",
    time: "3 weeks ago",
    depth: "12.8km",
    intensity: "Light",
    coordinates: { lat: 20.5937, lng: 72.9342 },
  },
  {
    id: 9,
    magnitude: 3.9,
    location: "Koyna, Maharashtra",
    time: "1 month ago",
    depth: "9.5km",
    intensity: "Light",
    coordinates: { lat: 17.3986, lng: 73.7539 },
  },
  {
    id: 10,
    magnitude: 4.1,
    location: "Sikkim-Nepal Border",
    time: "1 month ago",
    depth: "14.2km",
    intensity: "Light",
    coordinates: { lat: 27.533, lng: 88.5122 },
  },
]
